- Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [19]:
import numpy as np

In [20]:
def crear_array_dimension():    
    m = np.random.randint (0,50, size = (4))
    print(m)
    print("Tamaño total del array: ",(m.size)) 
    print("La forma del array es: ", (m.shape)) # forma
    print("El tipo del elementos en el array es: ", (m.dtype)) # tipo de sus elementos
    print("Las dimensiones del array son: ", (m.ndim))
    #if (m.ndim > 1) 
   # print("Error")
    print("El número mayor es: ", max(m))
    print("El número menor es: ", min(m))
    #print("El rango es: ", range(m))
    
crear_array_dimension()




[46 35 23 27]
Tamaño total del array:  4
La forma del array es:  (4,)
El tipo del elementos en el array es:  int32
Las dimensiones del array son:  1
El número mayor es:  46
El número menor es:  23


In [24]:
def crear_array_dimension():    
    m = np.random.randint (0,50, size = (4))
    print(m)
    print("Tamaño total del array: ",(m.size)) 
    print("La forma del array es: ", (m.shape)) # forma
    print("El tipo del elementos en el array es: ", (m.dtype)) # tipo de sus elementos
    print("Las dimensiones del array son: ", (m.ndim))
    dimension = m.ndim
    if dimension > 1: 
        print("Error")
    print("El número mayor es: ", max(m))
    print("El número menor es: ", min(m))
    #print("El rango es: ", range(m))
    
crear_array_dimension()

[31 49 23  4]
Tamaño total del array:  4
La forma del array es:  (4,)
El tipo del elementos en el array es:  int32
Las dimensiones del array son:  1
El número mayor es:  49
El número menor es:  4


In [40]:
def crear_array_dimension():    
    m = np.random.randint (0,50, size = (4,4))
    print(m)
    print("Tamaño total del array: ",(m.size)) 
    print("La forma del array es: ", (m.shape)) # forma
    print("El tipo del elementos en el array es: ", (m.dtype)) # tipo de sus elementos
    print("El número mayor es: ", (m.max))
    print("El número menor es: ", (m.min))
    #print("El rango es: ", range(m))
  
    dimension = m.ndim
    if dimension > 1: 
        print("Dimension: Error")
       # elif:  
            #print(m.ndim)
 
    
crear_array_dimension()

[[45  9 22  2]
 [49  7 11  5]
 [15 48 49 40]
 [35 14 39  2]]
Tamaño total del array:  16
La forma del array es:  (4, 4)
El tipo del elementos en el array es:  int32
El número mayor es:  <built-in method max of numpy.ndarray object at 0x000001DF6555C090>
El número menor es:  <built-in method min of numpy.ndarray object at 0x000001DF6555C090>
Dimension: Error


In [44]:
m.size # tamaño total del array
m.shape # forma
m.dtype # tipo de sus elementos

dtype('int32')

- Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


In [16]:
import numpy as np

In [18]:
def crear_array():    
    m = np.random.randint (0,100, size = (4,4))
    print(m)
    
crear_array()

[[ 2  1 94 98]
 [92 47 77 48]
 [49 67 33 87]
 [18 90  9 66]]


In [19]:
def crear_array():    
    m = np.random.randint (0,100, size = (4,4))
    print(m)
    
crear_array()

[[10 70 37 24]
 [55 97 67 89]
 [73 18  4 69]
 [ 0 65 64 65]]


In [20]:
def crear_array():    
    m = np.random.randint (0,100, size = (4,4))
    print(m)
    
crear_array()

[[56 91 40 44]
 [47 64 92 51]
 [28 79 30 14]
 [92 38 26 11]]


- Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.


b.sum (axis = 1) # Suma per Fila 
b.sum (axis = 0) # Suma per Columna  

In [2]:
import numpy as np

In [3]:
def crear_array_sumas():    
    m = np.random.randint (0,100, size = (4,4))
    m1 = m.sum (axis = 1) # Suma per Fila
    m2 = m.sum (axis = 0) # Suma per Columna    
    print(m)
    print("La suma por fila es: ",m1)
    print("La suma por columna es: ",m2)
    
crear_array_sumas()

[[98 48  9 40]
 [63 48 89 11]
 [ 1 93 93 53]
 [61 68 72 59]]
La suma por fila es:  [195 211 240 260]
La suma por columna es:  [223 257 263 163]


- Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.


In [1]:
import numpy as np
import pandas as pd

El coheficiente de correlación es un valor obtenido a partir de la relación entre dos variables. El objetivo de obtener tal valor es el buscar la medida en que dicho valor confirma o no la relación entre dichas variables; es decir, cómo el aumento de una de las variables afecta a la otra. Esto puede ser en modo positivo o negativo: si el aumento de una de las variables, aumenta a la segunda variable sería (positivo) o directo, por el contrario si el aumento de la primera variable disminuye a la segunda, se llamaría inverso o negativo.

In [18]:
def coeficient_de_correlacio(): 

    X = np.array([92, 3, 63])
    Y = np.array([20, 2, 15])
resultado = np.corrcoef(X,Y)
print(resultado)

coeficient_de_correlacio(); 



[[1.         0.99861019]
 [0.99861019 1.        ]]
